from typing import Optional

class Space:
    kind: str
    n: Optional[int]
    low: Optional[list[float]]
    high: Optional[list[float]]
    shape: Optional[list[int]]
    nvec: Optional[list[int]]

class CartPole:
    def __init__(self, max_steps: int = ...) -> None: ...
    def reset(self, seed: Optional[int] = ...) -> list[float]: ...
    def step(self, action: int) -> tuple[list[float], float, bool, bool]: ...
    def action_space(self) -> Space: ...
    def observation_space(self) -> Space: ...

class GridWorld:
    def __init__(self) -> None: ...
    def reset(self, seed: Optional[int] = ...) -> list[float]: ...
    def step(self, action: int) -> tuple[list[float], float, bool, bool]: ...
    def action_space(self) -> Space: ...
    def observation_space(self) -> Space: ...

class MountainCar:
    def __init__(self, max_steps: int = ...) -> None: ...
    def reset(self, seed: Optional[int] = ...) -> list[float]: ...
    def step(self, action: int) -> tuple[list[float], float, bool, bool]: ...
    def action_space(self) -> Space: ...
    def observation_space(self) -> Space: ...

class Pendulum:
    def __init__(self, max_steps: int = ...) -> None: ...
    def reset(self, seed: Optional[int] = ...) -> list[float]: ...
    def step(self, action: list[float]) -> tuple[list[float], float, bool, bool]: ...
    def action_space(self) -> Space: ...
    def observation_space(self) -> Space: ...

class MountainCarContinuous:
    def __init__(self, max_steps: int = ...) -> None: ...
    def reset(self, seed: Optional[int] = ...) -> list[float]: ...
    def step(self, action: list[float]) -> tuple[list[float], float, bool, bool]: ...
    def action_space(self) -> Space: ...
    def observation_space(self) -> Space: ...

class DQN:
    @staticmethod
    def train(
        env_name: str,
        episodes: int = ...,
        max_steps: int = ...,
        hidden_dim: int = ...,
        lr: float = ...,
        gamma: float = ...,
        double_dqn: bool = ...,
        log_path: Optional[str] = ...,
    ) -> "DQN": ...
    def predict(self, obs: list[float]) -> int: ...
    def train_steps(self) -> int: ...
