[package]
name = "rustforge-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.102"
clap = { version = "4", features = ["derive"] }
rustforge-autograd = { path = "../rustforge-autograd" }
rustforge-tensor = { path = "../rustforge-tensor" }
rustforge-nn = { path = "../rustforge-nn" }
rustforge-rl = { path = "../rustforge-rl" }
rustforge-dashboard = { path = "../rustforge-dashboard" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[[bin]]
name = "rustforge"
path = "src/main.rs"
